apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-virt-app
  namespace: jkeam
  labels:
    app: ocp-virt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-virt-app
  template:
    metadata:
      labels:
        app: ocp-virt-app
    spec:
      serviceAccountName: ocp-virt-app
      containers:
      - name: ocp-virt-app
        image: "quay.io/jkeam/openshift-virt-app@sha256:95a7623f0ae5e75417817d8ad588c1da43daaea947895dbed561edaff3e350a4"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 2
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocp-virt-app
  name: ocp-virt-app
  namespace: jkeam
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ocp-virt-app
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ocp-virt-app
  namespace: jkeam
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    name: ocp-virt-app
