[project]
name = "ocp-virt-app"
version = "1.0.0"
description = "Ocp Virt App"
dependencies = [
    "flask",
    "gunicorn",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
