apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jkeam

images:
- name: quay.io/jkeam/openshift-virt-app-api
  digest: sha256:52847f455f75562504be3b55e7ef18185f058ea7c12c789e825e280cf760cf02
- name: quay.io/jkeam/openshift-virt-app-web
  digest: sha256:11a6174a1d7677a84815fa6868d8019f3e42412cda5f13b851390c5598a32393

resources:
  - rbac.yaml
  - deployment-api.yaml
  - deployment-web.yaml
