apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jkeam

images:
- name: quay.io/jkeam/openshift-virt-app-api
  digest: sha256:ea611bcf04dcdba8267798b9ca9a6e08de4a37ee423d7960a28a6288f85516fa
- name: quay.io/jkeam/openshift-virt-app-web
  digest: sha256:a3ffd057cf472981d05ea53ab421f94d492b2e090d6e4e46aaed214a8375a7c8

resources:
  - rbac.yaml
  - deployment-api.yaml
  - deployment-web.yaml
