apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jkeam

images:
- name: quay.io/jkeam/openshift-virt-app-api
  digest: sha256:52847f455f75562504be3b55e7ef18185f058ea7c12c789e825e280cf760cf02
- name: quay.io/jkeam/openshift-virt-app-web
  digest: sha256:2f96cae287f6f56f3a8a799fd2e266ae492340ca1cc0c4f5cdb8088eedf362bb

resources:
  - rbac.yaml
  - deployment-api.yaml
  - deployment-web.yaml
