apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jkeam

images:
- name: quay.io/jkeam/openshift-virt-app-api
  digest: sha256:52847f455f75562504be3b55e7ef18185f058ea7c12c789e825e280cf760cf02
- name: quay.io/jkeam/openshift-virt-app-web
  digest: sha256:bf2982d9b4aabed16bf37d7bb45743082d823d3d6587a2892422be628dc64616

resources:
  - rbac.yaml
  - deployment-api.yaml
  - deployment-web.yaml
