apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jkeam

images:
- name: quay.io/jkeam/openshift-virt-app-api
  digest: sha256:52847f455f75562504be3b55e7ef18185f058ea7c12c789e825e280cf760cf02
- name: quay.io/jkeam/openshift-virt-app-web
  digest: sha256:a3ffd057cf472981d05ea53ab421f94d492b2e090d6e4e46aaed214a8375a7c8

resources:
  - rbac.yaml
  - deployment-api.yaml
  - deployment-web.yaml
