---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocp-virt-app-role
  namespace: jkeam
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-virt-app
  namespace: jkeam

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocp-virt-app-role-binding
subjects:
- kind: ServiceAccount
  name: ocp-virt-app
  namespace: jkeam
roleRef:
  kind: Role
  name: ocp-virt-app-role
  apiGroup: rbac.authorization.k8s.io
